feat: auto-join threads
Wynntils/Wynntils-Bot pull request #11
Opened 2022-02-08 17:23 UTC by DevChromium

2022-02-08 17:49 UTC, DevScyu requested changes

2022-02-08 17:49 UTC, DevScyu commented on src/events/threadCreate.ts
> +        logError(err);
logError will also do a console output, is the line above needed?

2022-02-08 17:49 UTC, DevScyu commented on src/events/threadCreate.ts
> +        const logChannel = thread.guild.channels.cache.find(c => c.name === "server-logs") as TextChannel
might want to add a if(logChannel) before trying to send the message, as the channel could not exist

2022-02-08 17:49 UTC, DevScyu commented on src/events/threadDelete.ts
> +        logError(err)
same as above

2022-02-08 17:49 UTC, DevScyu commented on src/events/threadDelete.ts
> +        const logChannel = thread.guild.channels.cache.find(c => c.name === "server-logs") as TextChannel
same as above, check if the channel actually exists

2022-02-08 17:49 UTC, DevScyu commented on src/events/threadCreate.ts
> +        ])
```suggestion
        const embed = styledEmbed()
            .setColor(0x72ed9e)
            .setTitle("Thread Notification")
            .setDescription("An thread has been created.")
            .addFields([
            {
                name: 'Name',
                value: thread.name,
                inline: true
            },
            {
                name: 'Owner',
                value: `<@${thread.ownerId}>`,
                inline: true
            },
            {
                name: 'Created at',
                value: `<t:${Math.floor(thread.createdTimestamp / 1000)}:R>`,
                inline: true
            },
        ])
```

2022-02-08 17:49 UTC, DevScyu commented on src/events/threadDelete.ts
> +        embed.addFields([
same as above

2022-02-08 21:30 UTC, DevScyu commented on src/events/threadCreate.ts
> +    consola.success(`Joined thread ${thread.name}`);
still need this message?

2022-04-14 19:16 UTC, closed without merging

2022-04-14 19:16 UTC, DevChromium commented
moved to https://github.com/Wynntils/Wynntils-Bot/pull/14