feat: Moderation commands
Wynntils/Wynntils-Bot pull request #14
Opened 2022-04-14 19:16 UTC by DevChromium

2022-04-17 22:34 UTC, RuKira requested changes

2022-04-17 22:34 UTC, RuKira commented on src/commands/BanCommand.ts
> +            return { content: 'User does not exist' }
This is a Ban Command, not a Kick Command, I recommend changing these return statements.

2022-04-17 22:34 UTC, DevChromium commented on src/commands/BanCommand.ts
> +            return { content: 'User does not exist' }
I forgor 💀

2022-04-17 22:40 UTC, RuKira approved these changes
Awaiting Scyu Response.

2022-05-24 00:16 UTC, DevScyu approved these changes

2022-05-24 00:16 UTC, merged