chore: update faq.json
Wynntils/Wynntils-Bot pull request #35
Opened 2024-08-13 23:16 UTC by Rafii2198

I updated many entries that needed updating.

Notable changes:
- Added .wynntils and Launchy mention to logs entry
- Rewritten Install entry, uses Looni's video and also points to Launchy
- Removed "Artemis" and just use Wynntils
- Rewritten Bugs entry to accommodate more to how we are doing it today
- Added more information in Version entry
- Fixed some typos

2024-08-15 14:06 UTC, HighCrit requested changes

2024-08-15 14:06 UTC, HighCrit commented on assets/faq.json
> +		"value": "We currently maintain one version of [Wynntils](https://github.com/Wynntils/Artemis/releases/latest) which currently supports Minecraft 1.21 and 1.21.1 and supports Fabric and Neoforge mo
```suggestion
		"value": "We currently maintain only one version of [Wynntils](https://github.com/Wynntils/Artemis/releases/latest) (previously referred to as Artemis) and currently supports Minecraft 1.21 and 1.21.1 for the Fabric and Neoforge mod loaders."
```

2024-08-15 14:06 UTC, HighCrit commented on assets/faq.json
> +		"value": "We currently maintain one version of [Wynntils](https://github.com/Wynntils/Artemis/releases/latest) which currently supports Minecraft 1.21 and 1.21.1 and supports Fabric and Neoforge mo
I don't think we should mention Legacy anymore otherwise people will ask questions regarding the 1.12 version not working.

2024-08-24 12:53 UTC, HighCrit approved these changes

2024-09-01 11:48 UTC, kristofbolyai approved these changes

2024-09-01 11:48 UTC, merged